---

## 
## Install base configuration for all servers 
##
- name: Install the minimum Ansible + Linux configuration
  hosts: all
  remote_user: root # It's important here

  roles:
    - base
    - terminal
